export interface UniverseTicker {
  ticker: string;
  name: string;
  sector: string;
  domain: string;
}

export const UNIVERSE: UniverseTicker[] = [
  // ── Tech ──────────────────────────────────────────────────────────────────
  { ticker: 'AAPL',  name: 'Apple',                  sector: 'Tech',          domain: 'apple.com' },
  { ticker: 'MSFT',  name: 'Microsoft',               sector: 'Tech',          domain: 'microsoft.com' },
  { ticker: 'GOOGL', name: 'Alphabet',                sector: 'Tech',          domain: 'google.com' },
  { ticker: 'AMZN',  name: 'Amazon',                  sector: 'Tech',          domain: 'amazon.com' },
  { ticker: 'META',  name: 'Meta Platforms',           sector: 'Tech',          domain: 'meta.com' },
  { ticker: 'TSLA',  name: 'Tesla',                   sector: 'Tech',          domain: 'tesla.com' },
  { ticker: 'NFLX',  name: 'Netflix',                 sector: 'Tech',          domain: 'netflix.com' },
  { ticker: 'CRM',   name: 'Salesforce',              sector: 'Tech',          domain: 'salesforce.com' },
  { ticker: 'ADBE',  name: 'Adobe',                   sector: 'Tech',          domain: 'adobe.com' },
  { ticker: 'CSCO',  name: 'Cisco',                   sector: 'Tech',          domain: 'cisco.com' },
  { ticker: 'IBM',   name: 'IBM',                     sector: 'Tech',          domain: 'ibm.com' },
  { ticker: 'ACN',   name: 'Accenture',               sector: 'Tech',          domain: 'accenture.com' },
  { ticker: 'INTU',  name: 'Intuit',                  sector: 'Tech',          domain: 'intuit.com' },
  { ticker: 'NOW',   name: 'ServiceNow',              sector: 'Tech',          domain: 'servicenow.com' },
  { ticker: 'ORCL',  name: 'Oracle',                  sector: 'Tech',          domain: 'oracle.com' },
  { ticker: 'UBER',  name: 'Uber',                    sector: 'Tech',          domain: 'uber.com' },
  { ticker: 'PANW',  name: 'Palo Alto Networks',      sector: 'Tech',          domain: 'paloaltonetworks.com' },
  // ── Semiconductors ────────────────────────────────────────────────────────
  { ticker: 'NVDA',  name: 'Nvidia',                  sector: 'Semiconductors', domain: 'nvidia.com' },
  { ticker: 'AVGO',  name: 'Broadcom',                sector: 'Semiconductors', domain: 'broadcom.com' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',  sector: 'Semiconductors', domain: 'amd.com' },
  { ticker: 'TXN',   name: 'Texas Instruments',       sector: 'Semiconductors', domain: 'ti.com' },
  { ticker: 'QCOM',  name: 'Qualcomm',                sector: 'Semiconductors', domain: 'qualcomm.com' },
  { ticker: 'AMAT',  name: 'Applied Materials',       sector: 'Semiconductors', domain: 'appliedmaterials.com' },
  { ticker: 'MU',    name: 'Micron Technology',       sector: 'Semiconductors', domain: 'micron.com' },
  { ticker: 'LRCX',  name: 'Lam Research',            sector: 'Semiconductors', domain: 'lamresearch.com' },
  { ticker: 'ADI',   name: 'Analog Devices',          sector: 'Semiconductors', domain: 'analog.com' },
  { ticker: 'KLAC',  name: 'KLA Corporation',         sector: 'Semiconductors', domain: 'kla.com' },
  { ticker: 'NXPI',  name: 'NXP Semiconductors',      sector: 'Semiconductors', domain: 'nxp.com' },
  // ── Healthcare ────────────────────────────────────────────────────────────
  { ticker: 'LLY',   name: 'Eli Lilly',               sector: 'Healthcare',    domain: 'lilly.com' },
  { ticker: 'UNH',   name: 'UnitedHealth Group',      sector: 'Healthcare',    domain: 'unitedhealthgroup.com' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',       sector: 'Healthcare',    domain: 'jnj.com' },
  { ticker: 'ABBV',  name: 'AbbVie',                  sector: 'Healthcare',    domain: 'abbvie.com' },
  { ticker: 'MRK',   name: 'Merck',                   sector: 'Healthcare',    domain: 'merck.com' },
  { ticker: 'PFE',   name: 'Pfizer',                  sector: 'Healthcare',    domain: 'pfizer.com' },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific',sector: 'Healthcare',    domain: 'thermofisher.com' },
  { ticker: 'ABT',   name: 'Abbott Laboratories',     sector: 'Healthcare',    domain: 'abbott.com' },
  { ticker: 'DHR',   name: 'Danaher',                 sector: 'Healthcare',    domain: 'danaher.com' },
  { ticker: 'AMGN',  name: 'Amgen',                   sector: 'Healthcare',    domain: 'amgen.com' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',      sector: 'Healthcare',    domain: 'intuitivesurgical.com' },
  { ticker: 'GILD',  name: 'Gilead Sciences',         sector: 'Healthcare',    domain: 'gilead.com' },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals',  sector: 'Healthcare',    domain: 'vrtx.com' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',    sector: 'Healthcare',    domain: 'bms.com' },
  { ticker: 'REGN',  name: 'Regeneron Pharmaceuticals',sector: 'Healthcare',   domain: 'regeneron.com' },
  { ticker: 'MDT',   name: 'Medtronic',               sector: 'Healthcare',    domain: 'medtronic.com' },
  { ticker: 'CVS',   name: 'CVS Health',              sector: 'Healthcare',    domain: 'cvshealth.com' },
  { ticker: 'ELV',   name: 'Elevance Health',         sector: 'Healthcare',    domain: 'elevancehealth.com' },
  { ticker: 'CI',    name: 'Cigna Group',             sector: 'Healthcare',    domain: 'cigna.com' },
  { ticker: 'HUM',   name: 'Humana',                  sector: 'Healthcare',    domain: 'humana.com' },
  // ── Consumer ──────────────────────────────────────────────────────────────
  { ticker: 'WMT',   name: 'Walmart',                 sector: 'Consumer',      domain: 'walmart.com' },
  { ticker: 'COST',  name: 'Costco',                  sector: 'Consumer',      domain: 'costco.com' },
  { ticker: 'HD',    name: 'Home Depot',              sector: 'Consumer',      domain: 'homedepot.com' },
  { ticker: 'KO',    name: 'Coca-Cola',               sector: 'Consumer',      domain: 'coca-cola.com' },
  { ticker: 'PEP',   name: 'PepsiCo',                 sector: 'Consumer',      domain: 'pepsico.com' },
  { ticker: 'PM',    name: 'Philip Morris',           sector: 'Consumer',      domain: 'pmi.com' },
  { ticker: 'MCD',   name: "McDonald's",              sector: 'Consumer',      domain: 'mcdonalds.com' },
  { ticker: 'LOW',   name: "Lowe's",                  sector: 'Consumer',      domain: 'lowes.com' },
  { ticker: 'MO',    name: 'Altria Group',            sector: 'Consumer',      domain: 'altria.com' },
  { ticker: 'NKE',   name: 'Nike',                    sector: 'Consumer',      domain: 'nike.com' },
  { ticker: 'SBUX',  name: 'Starbucks',               sector: 'Consumer',      domain: 'starbucks.com' },
  { ticker: 'TGT',   name: 'Target',                  sector: 'Consumer',      domain: 'target.com' },
  { ticker: 'PG',    name: 'Procter & Gamble',        sector: 'Consumer',      domain: 'pg.com' },
  { ticker: 'KHC',   name: 'Kraft Heinz',             sector: 'Consumer',      domain: 'kraftheinz.com' },
  // ── Finance ───────────────────────────────────────────────────────────────
  { ticker: 'BRK-B', name: 'Berkshire Hathaway',      sector: 'Finance',       domain: 'berkshirehathaway.com' },
  { ticker: 'JPM',   name: 'JPMorgan Chase',          sector: 'Finance',       domain: 'jpmorganchase.com' },
  { ticker: 'V',     name: 'Visa',                    sector: 'Finance',       domain: 'visa.com' },
  { ticker: 'MA',    name: 'Mastercard',              sector: 'Finance',       domain: 'mastercard.com' },
  { ticker: 'BAC',   name: 'Bank of America',         sector: 'Finance',       domain: 'bankofamerica.com' },
  { ticker: 'WFC',   name: 'Wells Fargo',             sector: 'Finance',       domain: 'wellsfargo.com' },
  { ticker: 'GS',    name: 'Goldman Sachs',           sector: 'Finance',       domain: 'goldmansachs.com' },
  { ticker: 'MS',    name: 'Morgan Stanley',          sector: 'Finance',       domain: 'morganstanley.com' },
  { ticker: 'BLK',   name: 'BlackRock',               sector: 'Finance',       domain: 'blackrock.com' },
  { ticker: 'SCHW',  name: 'Charles Schwab',          sector: 'Finance',       domain: 'schwab.com' },
  { ticker: 'AXP',   name: 'American Express',        sector: 'Finance',       domain: 'americanexpress.com' },
  { ticker: 'C',     name: 'Citigroup',               sector: 'Finance',       domain: 'citi.com' },
  { ticker: 'SPGI',  name: 'S&P Global',              sector: 'Finance',       domain: 'spglobal.com' },
  { ticker: 'COF',   name: 'Capital One',             sector: 'Finance',       domain: 'capitalone.com' },
  { ticker: 'CB',    name: 'Chubb',                   sector: 'Finance',       domain: 'chubb.com' },
  { ticker: 'USB',   name: 'US Bancorp',              sector: 'Finance',       domain: 'usbank.com' },
  // ── Energy ────────────────────────────────────────────────────────────────
  { ticker: 'XOM',   name: 'ExxonMobil',              sector: 'Energy',        domain: 'exxonmobil.com' },
  { ticker: 'CVX',   name: 'Chevron',                 sector: 'Energy',        domain: 'chevron.com' },
  { ticker: 'SLB',   name: 'SLB',                     sector: 'Energy',        domain: 'slb.com' },
  { ticker: 'COP',   name: 'ConocoPhillips',          sector: 'Energy',        domain: 'conocophillips.com' },
  { ticker: 'NEE',   name: 'NextEra Energy',          sector: 'Energy',        domain: 'nexteraenergy.com' },
  { ticker: 'SO',    name: 'Southern Company',        sector: 'Energy',        domain: 'southerncompany.com' },
  { ticker: 'DUK',   name: 'Duke Energy',             sector: 'Energy',        domain: 'duke-energy.com' },
  { ticker: 'EOG',   name: 'EOG Resources',           sector: 'Energy',        domain: 'eogresources.com' },
  // ── Industrial ────────────────────────────────────────────────────────────
  { ticker: 'GE',    name: 'GE Aerospace',            sector: 'Industrial',    domain: 'ge.com' },
  { ticker: 'CAT',   name: 'Caterpillar',             sector: 'Industrial',    domain: 'caterpillar.com' },
  { ticker: 'RTX',   name: 'RTX Corporation',         sector: 'Industrial',    domain: 'rtx.com' },
  { ticker: 'HON',   name: 'Honeywell',               sector: 'Industrial',    domain: 'honeywell.com' },
  { ticker: 'ETN',   name: 'Eaton',                   sector: 'Industrial',    domain: 'eaton.com' },
  { ticker: 'LMT',   name: 'Lockheed Martin',         sector: 'Industrial',    domain: 'lockheedmartin.com' },
  { ticker: 'DE',    name: 'Deere & Company',         sector: 'Industrial',    domain: 'deere.com' },
  { ticker: 'UPS',   name: 'United Parcel Service',   sector: 'Industrial',    domain: 'ups.com' },
  { ticker: 'MMM',   name: '3M',                      sector: 'Industrial',    domain: '3m.com' },
  { ticker: 'ITW',   name: 'Illinois Tool Works',     sector: 'Industrial',    domain: 'itw.com' },
  { ticker: 'EMR',   name: 'Emerson Electric',        sector: 'Industrial',    domain: 'emerson.com' },
  { ticker: 'BA',    name: 'Boeing',                  sector: 'Industrial',    domain: 'boeing.com' },
  // ── Other ─────────────────────────────────────────────────────────────────
  { ticker: 'T',     name: 'AT&T',                    sector: 'Other',         domain: 'att.com' },
  { ticker: 'VZ',    name: 'Verizon',                 sector: 'Other',         domain: 'verizon.com' },
];

export const UNIVERSE_TICKERS = UNIVERSE.map((u) => u.ticker);
